# NOTE, THIS IS NOT A GOOD WAY OF KEEPING SECRET. THIS FILE SHOULD BE HIDDEN. (ADDITIONALY, NOT THE SAFEST PASSWORD MEASURES ARE IN PLACE).

PASSWORD_SALT = 'SIbDC2mqCX1zTUsBOLpQ'

JWT_SECRET = 'HQXNDEUWHLgiWKzW5uc3'